### ISSUE TITLE
Compile failed with the latest serde_codegen v0.7.0

### ISSUE THREAD

**Issue by fengsp** [mikedilger/textnonce#6]
`error: no method named `deserialize_newtype_struct` found for type `&mut __D` in the current scope`

**Comment by SkylerLipthay** [comment]
Unfortunately, `^0` is problematic. Serde 0.7 is not backwards compatible with 0.6, so the Serde dependencies should be set to `0.7`.

More generally, while SemVer requires a major version bump for breaking changes for versions `>= 1.0.0`, it allows breaking changes between minor version releases for versions `< 1.0.0`. ["0.x and 0.x+1 are not considered compatible, but 1.x and 1.x+1 are."](https://github.com/steveklabnik/semver)

For this reason, specifying `0` or `^0` is an anti-pattern.

So what ended up happening to someone in IRC and me is that `serde_codegen 0.7` was being used alongside `serde 0.6` by `textnonce`, because the version rules were relaxed enough for Cargo to decide that was okay. This resulted in [this compile error](http://pastebin.com/JciLCsbP).

I recommend `cargo yank`ing the affected versions (`0.2.3` and `0.2.4`, I believe) of textnonce and releasing `0.2.5` with the fixed dependencies. Similarly, Syntex's minor version should be specified in Cargo.toml.
